package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"time"

	// Import the docs generated by Swag
	_ "inventory-supply-chain-system/cmd/docs"

	"github.com/gorilla/mux"
	"github.com/joho/godotenv"
	httpSwagger "github.com/swaggo/http-swagger"

	"inventory-supply-chain-system/controllers"
	"inventory-supply-chain-system/db"
	"inventory-supply-chain-system/internal/middlewares"
	"inventory-supply-chain-system/routes"
)

// @title Enterprise Inventory and Supply Chain Management System API
// @version 1.0
// @description These are APIs for the Enterprise Inventory and Supply Chain Management System.
// @host localhost:8080
// @BasePath /api
func main() {
	// Load the .env file
	err := godotenv.Load()
	if err != nil {
		log.Fatalf("Error loading .env file: %v", err)
	}

	// Log environment variables for debugging
	log.Println("DB_HOST:", os.Getenv("DB_HOST"))
	log.Println("DB_USER:", os.Getenv("DB_USER"))
	log.Println("DB_NAME:", os.Getenv("DB_NAME"))
	log.Println("DB_PORT:", os.Getenv("DB_PORT"))

	// Initialize the database connection
	db.ConnectDB()

	// Create a new router
	r := mux.NewRouter()

	// Public routes
	r.HandleFunc("/api/auth/register", controllers.RegisterUser).Methods("POST")
	r.HandleFunc("/api/auth/login", controllers.LoginUser).Methods("POST")

	// Swagger route for API docs
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	// Protected routes (Require authentication)
	api := r.PathPrefix("/api").Subrouter()
	api.Use(middlewares.AuthMiddleware)

	// Register protected routes
	routes.RegisterItemRoutes(api)
	routes.RegisterProductRoutes(api)
	routes.RegisterProfileRoutes(api)
	routes.RegisterSupplierRoutes(api)
	routes.RegisterOrderRoutes(api)
	routes.RegisterInventoryRoutes(api)
	routes.RegisterShipmentRoutes(api)
	routes.RegisterVendorRoutes(api)

	// Serve static files
	r.PathPrefix("/static/").Handler(http.StripPrefix("/static/", http.FileServer(http.Dir("static"))))
	r.PathPrefix("/").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "static/index.html")
	})

	// Handle 404
	r.NotFoundHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "static/404.html")
	})

	// Handle 405
	r.MethodNotAllowedHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "static/405.html")
	})

	// Middleware to handle panics and recover with error pages
	r.Use(recoverMiddleware)

	// Create the server
	srv := &http.Server{
		Addr:    ":8080",
		Handler: r,
	}

	// Start the server in a goroutine
	go func() {
		log.Println("The ISCS Server is running on port 8080")
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("listen: %s\n", err)
		}
	}()

	// Wait for interrupt signal to gracefully shut down the server
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, os.Interrupt)
	<-quit

	log.Println("Shutting down ISCS server...")

	// Create a context for the shutdown process with a timeout of 5 seconds
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := srv.Shutdown(ctx); err != nil {
		log.Fatal("ISCS Server forced to shutdown:", err)
	}

	log.Println("ISCS Server exiting")
}

// recoverMiddleware handles panics and recovers with appropriate error pages.
func recoverMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if rec := recover(); rec != nil {
				log.Printf("I have recovered from panic: %v", rec)
				http.ServeFile(w, r, "static/500.html")
			}
		}()
		next.ServeHTTP(w, r)
	})
}
