basePath: /api
host: localhost:8080
info:
  contact: {}
  description: These are APIs for the Enterprise Inventory and Supply Chain Management
    System.
  title: Enterprise Inventory and Supply Chain Management System API
  version: "1.0"
paths: {}
swagger: "2.0"
